// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: patterns/p04/proto/work.proto

package gen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkDistribution_Connect_FullMethodName = "/work.WorkDistribution/Connect"
)

// WorkDistributionClient is the client API for WorkDistribution service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorkDistribution service: Manager -> Worker bidirectional streaming
type WorkDistributionClient interface {
	// Connect establishes a bidirectional stream between Manager and Worker
	// Manager sends Tasks down; Worker sends TaskEvents up
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TaskEvent, Task], error)
}

type workDistributionClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkDistributionClient(cc grpc.ClientConnInterface) WorkDistributionClient {
	return &workDistributionClient{cc}
}

func (c *workDistributionClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TaskEvent, Task], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkDistribution_ServiceDesc.Streams[0], WorkDistribution_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TaskEvent, Task]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkDistribution_ConnectClient = grpc.BidiStreamingClient[TaskEvent, Task]

// WorkDistributionServer is the server API for WorkDistribution service.
// All implementations must embed UnimplementedWorkDistributionServer
// for forward compatibility.
//
// WorkDistribution service: Manager -> Worker bidirectional streaming
type WorkDistributionServer interface {
	// Connect establishes a bidirectional stream between Manager and Worker
	// Manager sends Tasks down; Worker sends TaskEvents up
	Connect(grpc.BidiStreamingServer[TaskEvent, Task]) error
	mustEmbedUnimplementedWorkDistributionServer()
}

// UnimplementedWorkDistributionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkDistributionServer struct{}

func (UnimplementedWorkDistributionServer) Connect(grpc.BidiStreamingServer[TaskEvent, Task]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedWorkDistributionServer) mustEmbedUnimplementedWorkDistributionServer() {}
func (UnimplementedWorkDistributionServer) testEmbeddedByValue()                          {}

// UnsafeWorkDistributionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkDistributionServer will
// result in compilation errors.
type UnsafeWorkDistributionServer interface {
	mustEmbedUnimplementedWorkDistributionServer()
}

func RegisterWorkDistributionServer(s grpc.ServiceRegistrar, srv WorkDistributionServer) {
	// If the following call panics, it indicates UnimplementedWorkDistributionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkDistribution_ServiceDesc, srv)
}

func _WorkDistribution_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkDistributionServer).Connect(&grpc.GenericServerStream[TaskEvent, Task]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkDistribution_ConnectServer = grpc.BidiStreamingServer[TaskEvent, Task]

// WorkDistribution_ServiceDesc is the grpc.ServiceDesc for WorkDistribution service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkDistribution_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "work.WorkDistribution",
	HandlerType: (*WorkDistributionServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _WorkDistribution_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "patterns/p04/proto/work.proto",
}

const (
	TaskManager_Submit_FullMethodName    = "/work.TaskManager/Submit"
	TaskManager_Get_FullMethodName       = "/work.TaskManager/Get"
	TaskManager_List_FullMethodName      = "/work.TaskManager/List"
	TaskManager_Subscribe_FullMethodName = "/work.TaskManager/Subscribe"
)

// TaskManagerClient is the client API for TaskManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TaskManager service: API -> Manager
type TaskManagerClient interface {
	// Submit creates a new task
	Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*SubmitResponse, error)
	// Get retrieves a task by ID
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// List returns all tasks
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	// Subscribe streams events for a specific task or all tasks
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskEvent], error)
}

type taskManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskManagerClient(cc grpc.ClientConnInterface) TaskManagerClient {
	return &taskManagerClient{cc}
}

func (c *taskManagerClient) Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*SubmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitResponse)
	err := c.cc.Invoke(ctx, TaskManager_Submit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskManagerClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, TaskManager_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskManagerClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, TaskManager_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskManagerClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TaskManager_ServiceDesc.Streams[0], TaskManager_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, TaskEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskManager_SubscribeClient = grpc.ServerStreamingClient[TaskEvent]

// TaskManagerServer is the server API for TaskManager service.
// All implementations must embed UnimplementedTaskManagerServer
// for forward compatibility.
//
// TaskManager service: API -> Manager
type TaskManagerServer interface {
	// Submit creates a new task
	Submit(context.Context, *SubmitRequest) (*SubmitResponse, error)
	// Get retrieves a task by ID
	Get(context.Context, *GetRequest) (*GetResponse, error)
	// List returns all tasks
	List(context.Context, *ListRequest) (*ListResponse, error)
	// Subscribe streams events for a specific task or all tasks
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[TaskEvent]) error
	mustEmbedUnimplementedTaskManagerServer()
}

// UnimplementedTaskManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskManagerServer struct{}

func (UnimplementedTaskManagerServer) Submit(context.Context, *SubmitRequest) (*SubmitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Submit not implemented")
}
func (UnimplementedTaskManagerServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedTaskManagerServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedTaskManagerServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[TaskEvent]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedTaskManagerServer) mustEmbedUnimplementedTaskManagerServer() {}
func (UnimplementedTaskManagerServer) testEmbeddedByValue()                     {}

// UnsafeTaskManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskManagerServer will
// result in compilation errors.
type UnsafeTaskManagerServer interface {
	mustEmbedUnimplementedTaskManagerServer()
}

func RegisterTaskManagerServer(s grpc.ServiceRegistrar, srv TaskManagerServer) {
	// If the following call panics, it indicates UnimplementedTaskManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskManager_ServiceDesc, srv)
}

func _TaskManager_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskManagerServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskManager_Submit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskManagerServer).Submit(ctx, req.(*SubmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskManager_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskManagerServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskManager_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskManagerServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskManager_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskManagerServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskManager_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskManagerServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskManager_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TaskManagerServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, TaskEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskManager_SubscribeServer = grpc.ServerStreamingServer[TaskEvent]

// TaskManager_ServiceDesc is the grpc.ServiceDesc for TaskManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "work.TaskManager",
	HandlerType: (*TaskManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Submit",
			Handler:    _TaskManager_Submit_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _TaskManager_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _TaskManager_List_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _TaskManager_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "patterns/p04/proto/work.proto",
}
