// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: patterns/p04/proto/work.proto

package gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Stage represents a single processing step within a task
type Stage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DurationMs    int32                  `protobuf:"varint,2,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Error         *string                `protobuf:"bytes,4,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stage) Reset() {
	*x = Stage{}
	mi := &file_patterns_p04_proto_work_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stage) ProtoMessage() {}

func (x *Stage) ProtoReflect() protoreflect.Message {
	mi := &file_patterns_p04_proto_work_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stage.ProtoReflect.Descriptor instead.
func (*Stage) Descriptor() ([]byte, []int) {
	return file_patterns_p04_proto_work_proto_rawDescGZIP(), []int{0}
}

func (x *Stage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stage) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *Stage) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Stage) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// Task represents a work item
type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Stages        []*Stage               `protobuf:"bytes,4,rep,name=stages,proto3" json:"stages,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_patterns_p04_proto_work_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_patterns_p04_proto_work_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_patterns_p04_proto_work_proto_rawDescGZIP(), []int{1}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Task) GetStages() []*Stage {
	if x != nil {
		return x.Stages
	}
	return nil
}

func (x *Task) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Task) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// TaskEvent represents a status update or progress event
type TaskEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	StageName     *string                `protobuf:"bytes,4,opt,name=stage_name,json=stageName,proto3,oneof" json:"stage_name,omitempty"`
	Progress      *int32                 `protobuf:"varint,5,opt,name=progress,proto3,oneof" json:"progress,omitempty"`
	Error         *string                `protobuf:"bytes,6,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskEvent) Reset() {
	*x = TaskEvent{}
	mi := &file_patterns_p04_proto_work_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEvent) ProtoMessage() {}

func (x *TaskEvent) ProtoReflect() protoreflect.Message {
	mi := &file_patterns_p04_proto_work_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEvent.ProtoReflect.Descriptor instead.
func (*TaskEvent) Descriptor() ([]byte, []int) {
	return file_patterns_p04_proto_work_proto_rawDescGZIP(), []int{2}
}

func (x *TaskEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *TaskEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskEvent) GetStageName() string {
	if x != nil && x.StageName != nil {
		return *x.StageName
	}
	return ""
}

func (x *TaskEvent) GetProgress() int32 {
	if x != nil && x.Progress != nil {
		return *x.Progress
	}
	return 0
}

func (x *TaskEvent) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *TaskEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Request/Response messages for TaskManager service (API -> Manager)
type SubmitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRequest) Reset() {
	*x = SubmitRequest{}
	mi := &file_patterns_p04_proto_work_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequest) ProtoMessage() {}

func (x *SubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patterns_p04_proto_work_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequest.ProtoReflect.Descriptor instead.
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return file_patterns_p04_proto_work_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type SubmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponse) Reset() {
	*x = SubmitResponse{}
	mi := &file_patterns_p04_proto_work_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponse) ProtoMessage() {}

func (x *SubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patterns_p04_proto_work_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return file_patterns_p04_proto_work_proto_rawDescGZIP(), []int{4}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_patterns_p04_proto_work_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patterns_p04_proto_work_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_patterns_p04_proto_work_proto_rawDescGZIP(), []int{5}
}

func (x *GetRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_patterns_p04_proto_work_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patterns_p04_proto_work_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_patterns_p04_proto_work_proto_rawDescGZIP(), []int{6}
}

func (x *GetResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_patterns_p04_proto_work_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patterns_p04_proto_work_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_patterns_p04_proto_work_proto_rawDescGZIP(), []int{7}
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_patterns_p04_proto_work_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patterns_p04_proto_work_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_patterns_p04_proto_work_proto_rawDescGZIP(), []int{8}
}

func (x *ListResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        *string                `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3,oneof" json:"task_id,omitempty"` // Empty for global subscription
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_patterns_p04_proto_work_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patterns_p04_proto_work_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_patterns_p04_proto_work_proto_rawDescGZIP(), []int{9}
}

func (x *SubscribeRequest) GetTaskId() string {
	if x != nil && x.TaskId != nil {
		return *x.TaskId
	}
	return ""
}

var File_patterns_p04_proto_work_proto protoreflect.FileDescriptor

const file_patterns_p04_proto_work_proto_rawDesc = "" +
	"\n" +
	"\x1dpatterns/p04/proto/work.proto\x12\x04work\"y\n" +
	"\x05Stage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vduration_ms\x18\x02 \x01(\x05R\n" +
	"durationMs\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x19\n" +
	"\x05error\x18\x04 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\xa7\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12#\n" +
	"\x06stages\x18\x04 \x03(\v2\v.work.StageR\x06stages\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\"\xff\x01\n" +
	"\tTaskEvent\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\"\n" +
	"\n" +
	"stage_name\x18\x04 \x01(\tH\x00R\tstageName\x88\x01\x01\x12\x1f\n" +
	"\bprogress\x18\x05 \x01(\x05H\x01R\bprogress\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\x06 \x01(\tH\x02R\x05error\x88\x01\x01\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestampB\r\n" +
	"\v_stage_nameB\v\n" +
	"\t_progressB\b\n" +
	"\x06_error\"/\n" +
	"\rSubmitRequest\x12\x1e\n" +
	"\x04task\x18\x01 \x01(\v2\n" +
	".work.TaskR\x04task\"\x10\n" +
	"\x0eSubmitResponse\"%\n" +
	"\n" +
	"GetRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"C\n" +
	"\vGetResponse\x12\x1e\n" +
	"\x04task\x18\x01 \x01(\v2\n" +
	".work.TaskR\x04task\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"\r\n" +
	"\vListRequest\"0\n" +
	"\fListResponse\x12 \n" +
	"\x05tasks\x18\x01 \x03(\v2\n" +
	".work.TaskR\x05tasks\"<\n" +
	"\x10SubscribeRequest\x12\x1c\n" +
	"\atask_id\x18\x01 \x01(\tH\x00R\x06taskId\x88\x01\x01B\n" +
	"\n" +
	"\b_task_id2>\n" +
	"\x10WorkDistribution\x12*\n" +
	"\aConnect\x12\x0f.work.TaskEvent\x1a\n" +
	".work.Task(\x010\x012\xd5\x01\n" +
	"\vTaskManager\x123\n" +
	"\x06Submit\x12\x13.work.SubmitRequest\x1a\x14.work.SubmitResponse\x12*\n" +
	"\x03Get\x12\x10.work.GetRequest\x1a\x11.work.GetResponse\x12-\n" +
	"\x04List\x12\x11.work.ListRequest\x1a\x12.work.ListResponse\x126\n" +
	"\tSubscribe\x12\x16.work.SubscribeRequest\x1a\x0f.work.TaskEvent0\x01B7Z5work-distribution-patterns/patterns/p04/proto/gen;genb\x06proto3"

var (
	file_patterns_p04_proto_work_proto_rawDescOnce sync.Once
	file_patterns_p04_proto_work_proto_rawDescData []byte
)

func file_patterns_p04_proto_work_proto_rawDescGZIP() []byte {
	file_patterns_p04_proto_work_proto_rawDescOnce.Do(func() {
		file_patterns_p04_proto_work_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_patterns_p04_proto_work_proto_rawDesc), len(file_patterns_p04_proto_work_proto_rawDesc)))
	})
	return file_patterns_p04_proto_work_proto_rawDescData
}

var file_patterns_p04_proto_work_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_patterns_p04_proto_work_proto_goTypes = []any{
	(*Stage)(nil),            // 0: work.Stage
	(*Task)(nil),             // 1: work.Task
	(*TaskEvent)(nil),        // 2: work.TaskEvent
	(*SubmitRequest)(nil),    // 3: work.SubmitRequest
	(*SubmitResponse)(nil),   // 4: work.SubmitResponse
	(*GetRequest)(nil),       // 5: work.GetRequest
	(*GetResponse)(nil),      // 6: work.GetResponse
	(*ListRequest)(nil),      // 7: work.ListRequest
	(*ListResponse)(nil),     // 8: work.ListResponse
	(*SubscribeRequest)(nil), // 9: work.SubscribeRequest
}
var file_patterns_p04_proto_work_proto_depIdxs = []int32{
	0, // 0: work.Task.stages:type_name -> work.Stage
	1, // 1: work.SubmitRequest.task:type_name -> work.Task
	1, // 2: work.GetResponse.task:type_name -> work.Task
	1, // 3: work.ListResponse.tasks:type_name -> work.Task
	2, // 4: work.WorkDistribution.Connect:input_type -> work.TaskEvent
	3, // 5: work.TaskManager.Submit:input_type -> work.SubmitRequest
	5, // 6: work.TaskManager.Get:input_type -> work.GetRequest
	7, // 7: work.TaskManager.List:input_type -> work.ListRequest
	9, // 8: work.TaskManager.Subscribe:input_type -> work.SubscribeRequest
	1, // 9: work.WorkDistribution.Connect:output_type -> work.Task
	4, // 10: work.TaskManager.Submit:output_type -> work.SubmitResponse
	6, // 11: work.TaskManager.Get:output_type -> work.GetResponse
	8, // 12: work.TaskManager.List:output_type -> work.ListResponse
	2, // 13: work.TaskManager.Subscribe:output_type -> work.TaskEvent
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_patterns_p04_proto_work_proto_init() }
func file_patterns_p04_proto_work_proto_init() {
	if File_patterns_p04_proto_work_proto != nil {
		return
	}
	file_patterns_p04_proto_work_proto_msgTypes[0].OneofWrappers = []any{}
	file_patterns_p04_proto_work_proto_msgTypes[2].OneofWrappers = []any{}
	file_patterns_p04_proto_work_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_patterns_p04_proto_work_proto_rawDesc), len(file_patterns_p04_proto_work_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_patterns_p04_proto_work_proto_goTypes,
		DependencyIndexes: file_patterns_p04_proto_work_proto_depIdxs,
		MessageInfos:      file_patterns_p04_proto_work_proto_msgTypes,
	}.Build()
	File_patterns_p04_proto_work_proto = out.File
	file_patterns_p04_proto_work_proto_goTypes = nil
	file_patterns_p04_proto_work_proto_depIdxs = nil
}
